# gitpod.yml
# Configuration file for Gitpod to automate the setup and runtime of the Honeycomb project

# Tasks to run when the workspace starts
tasks:
  # Initial setup: Install dependencies
  - init: npm install
  # Command to start the development server
  - command: |
      echo "Starting Vite server..."
      npm run dev

# VSCode extensions for development environment
vscode:
  extensions:
    - dbaeumer.vscode-eslint      # ESLint for linting JavaScript/TypeScript
    - esbenp.prettier-vscode      # Prettier for code formatting

# Port configuration
ports:
  - port: 5173
    onOpen: open-preview         # Open port 5173 in preview mode when the server starts
    visibility: public           # Make the port publicly accessible (required for Gitpod URLs)

# Environment variables (optional, if custom variables are needed instead of GITPOD_WORKSPACE_URL)
env:
  # Optionally set a custom variable if GITPOD_WORKSPACE_URL is unreliable
  MY_WORKSPACE_URL: 5173-vandex186-honeycomb-vjhec9j9f3ws-us120.gitpod.io

# Git configuration (optional, to set user details)
# gitConfig:
#   - name: user.name
#     value: "Your Name"           # Replace with your name
#   - name: user.email
#     value: "your.email@example.com" # Replace with your email

# Checkout configuration (optional, to specify branch or repository settings)
checkoutLocation: .

# Image configuration (optional, to use a specific base image)
image:
  file: .gitpod.Dockerfile      # Reference a custom Dockerfile if needed (see below)

# Optional: Custom Dockerfile for specific dependencies
# Uncomment and create .gitpod.Dockerfile if you need a custom image
#image:
#  file: .gitpod.Dockerfile

# Optional: Persistent volume for storing build artifacts or cache
#volumes:
#  - name: npm-cache
#    path: /home/gitpod/.npm
