---
image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
  - command: npm run dev

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode