# Gitpod configuration for honeycomb project
image:
  file: .gitpod.Dockerfile

# Ports to expose
ports:
  - port: 5173
    onOpen: open
    name: "Vite Dev Server"
    description: "Development server for the application"
  - port: 4173
    onOpen: notify
    name: "Vite Preview Server"
    description: "Preview server for production build"
  - port: 3000
    onOpen: ignore
    name: "Additional Dev Port"
  - port: 8080
    onOpen: ignore
    name: "Preview Port"

# Tasks to run on workspace startup - FRESH INSTALL EVERY TIME
tasks:
  - name: "Fresh Install and Setup"
    init: |
      # Remove any existing node_modules, cache, and lock files for fresh start
      rm -rf node_modules package-lock.json .npm .cache .vite
      # Fresh npm install without any caching
      npm install --no-cache
      echo "Fresh dependencies installed!"
    command: |
      echo "Fresh workspace ready for development!"
      echo "Dependencies freshly installed (no cache)"
      echo "Run 'npm run dev' to start the development server"
      echo "Run 'npm run build' to build for production"
      echo "Run 'npm run preview' to preview the production build"
      echo "Your dev server will be available at port 5173"

# VS Code extensions to install
vscode:
  extensions:
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-json
    - formulahendry.auto-rename-tag
    - ms-vscode.vscode-eslint
    - ms-vscode.vscode-npm-script
    - ms-vscode.vscode-css-peek
    - christian-kohler.path-intellisense

# GitHub prebuilds
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
