---
image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose up -d

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker