---
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Task runner if not available
      if ! command -v task &> /dev/null; then
        curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b ~/.local/bin
        export PATH="$PATH:~/.local/bin"
      fi
      # Run prebuild setup
      task gitpod:prebuild
    command: bash scripts/gitpod-start.sh

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker