---
image:
  file: .gitpod.Dockerfile

tasks:
  - init: pnpm install
  - command: pnpm add -D @types/node && pnpm run dev

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode