all:
  children:
    production:
      hosts:
        contabo-server:
          ansible_host: YOUR_CONTABO_IP_HERE
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
          domain: your-domain.com
          app_name: honeycomb
          app_port: 3000
          nginx_port: 80
          ssl_enabled: true 